name: "[Dispatch] Release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'enter version(x.y.z)'
        required: true
        default: '1.0.0'


env:
  VERSION: ${{ github.event.inputs.version }}
  PACKAGE_VERSION: ${{ github.event.inputs.version }}
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SAMUEL_TOKEN }}

      - name: tagging
        run: |
          git config user.email pyt4105@gmail.com
          git config user.name piggggggggy
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}

  pypi:
    needs: tagging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SAMUEL_TOKEN }}

      - name: Set python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install setuptools wheel twine

      - name: Make all and Packaging
        run: |
          cd src
          python setup.py sdist bdist_wheel

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
          packages-dir: src/dist/

